language: node_js

node_js: 
  - "6"

env: 
 - NODE_ENV="development"

before_script:
  - npm install -g gulp

script: gulp travis

after_success: ./node_modules/.bin/coveralls --verbose < test/coverage/lcov.info
